# Generated by Django 2.2 on 2020-06-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_auto_20200227_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
